# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pilots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100, null=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.Expansions')),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.Expansions')),
            ],
        ),
        migrations.AddField(
            model_name='pilots',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.Ships'),
        ),
    ]
