# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilots',
            name='isUnique',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilots',
            name='pilotCost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilots',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ships',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
