# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadbuilder', '0002_auto_20160422_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilots',
            name='faction',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
