# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadbuilder', '0003_pilots_faction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('upgradeCost', models.IntegerField()),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.Expansions')),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='upgrades',
            name='upgradetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.UpgradeTypes'),
        ),
    ]
