# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadbuilder', '0004_auto_20160501_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot2Upgrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.Pilots')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.UpgradeTypes')),
            ],
        ),
        migrations.AddField(
            model_name='upgrades',
            name='isUnique',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
