# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadbuilder', '0005_auto_20160501_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='ships',
            name='faction',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
