# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadbuilder', '0010_auto_20160703_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade', models.CharField(max_length=50)),
                ('bonus_type', models.CharField(max_length=10)),
                ('bonus_quantity', models.IntegerField()),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadbuilder.UpgradeTypes')),
            ],
        ),
    ]
