# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsquads',
            name='upvotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
