# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 05:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squadshare', '0002_savedsquads_upvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squadshare.SavedSquads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
