# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 06:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadshare', '0003_squadcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadcomments',
            name='commentDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
