# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadshare', '0005_userupvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsquads',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
