from squadbuilder.models import UpgradeRestrictions

additions=[('4-LOM','Scum','Faction'),
           ('Advanced Cloaking Device','TIE-Phantom','Ship'),
           ('Andrasta','Firespray-31','Ship'),
           ('Anti Pursuit Laser','Large','Size'),
           ('Attanni Mindlink','Scum','Faction'),
           ('Autothrusters','Boost','Action'),
           ('Boba Fett','Scum','Faction'),
           ('Bodyguard','Scum','Faction'),
           ('Bomb Loadout','Y-Wing','Ship'),
           ('Bossk','Scum','Faction'),
           ('BTL-A4 Y-wing','Y-Wing','Ship'),
           ('Chewbacca','Rebel','Faction'),
           ('Chopper','Rebel','Faction'),
           ('Cloaking Device','Small','Size'),
           ('Counter-Measures','Large','Size'),
           ('Darth Vader','Empire','Faction'),
           ('Dash Rendar','Rebel','Faction'),
           ('Dauntless','VT-49-Decimator','Ship'),
           ('Dengar','Scum','Faction'),
           ('Ezra Bridger','Rebel','Faction'),
           ('Fleet Officer','Empire','Faction'),
           ('Ghost','VCX-100','Ship'),
           ('Gonk','Scum','Faction'),
           ('Greedo','Scum','Faction'),
           ('Heavy Scyk Interceptor','M3-A-Interceptor','Ship'),
           ('Hera Syndulla','Rebel','Faction'),
           ('Hound\'s Tooth','YV-666-freighter','Ship'),
           ('IG-2000','Aggressor-assualt-fighter ','Ship'),
           ('Integrated Astromech','X-Wing','Ship'),
           ('Ion Projector','Large','Size'),
           ('Juke','Small','Size'),
           ('K4 Security Droid','Scum','Faction'),
           ('Kanan Jarrus','Rebel','Faction'),
           ('Lando Calrissian','Rebel','Faction'),
           ('Leebo','Rebel','Faction'),
           ('Lightning Reflexes','Small','Size'),
           ('Luke Skywalker','Rebel','Faction'),
           ('Maneuvering Fins','YV-666-freighter','Ship'),
           ('Mara Jade','Empire','Faction'),
           ('Millennium Falcon','YT-1300','Ship'),
           ('Mist Hunter','G-1A-Starfighter','Ship'),
           ('Moff Jerjerrod','Empire','Faction'),
           ('Moldy Crow','HWK-290','Ship'),
           ('Nien Nunb','Rebel','Faction'),
           ('Outlaw Tech','Scum','Faction'),
           ('Outrider','YT-2400','Ship'),
           ('Phantom','Attack-Shuttle','Ship'),
           ('Punishing One','JumpMaster-5000','Ship'),
           ('Rebel Captive','Empire','Faction'),
           ('Reinforced Deflectors','Large','Size'),
           ('Ruthlessness','Empire','Faction'),
           ('Sabine Wren','Rebel','Faction'),
           ('Slave 1','Firespray-31','Ship'),
           ('ST-321','Lambda-class-Shuttle','Ship'),
           ('Tactical Jammer','Large','Size'),
           ('TIE/v1','TIE-Advaced-Prototype','Ship'),
           ('Twin Ion Engine Mk. II','TIE','Ship'),
           ('Virago','StarViper','Ship'),
           ('Ysanne Isard','Empire','Faction'),
           ('Zeb Orrelios','Rebel','Faction'),
           ('Zuckuss','Scum','Faction')]

for upgrade in additions:
    sql_add = UpgradeRestrictions(upgrade=upgrade[0],restriction=upgrade[1],restriction_type=upgrade[2])
    sql_add.save()
